### ISSUE TITLE
Demo custom form components

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/form-playground#106]
__What should we do?__

Create an easy way to demo and test custom form components.

* [ ] Upload form component extension into the Playground Demo, this includes
  * [ ] Rendering extension
  * [ ] Properties Panel extension
  * [ ] Custom styles
* [ ] Deploy demo and gather feedback

__Why should we do it?__

Related to https://github.com/bpmn-io/form-js/issues/123

**Comment by pinussilvestrus** [comment]
A basic demo is available via https://106-custom-form-components--camunda-form-playground.netlify.app/

* Upload extension into the environment, consists of
  * Rendering extension
  * Properties Panel extension
  * Custom styles
  
This [example extension](https://github.com/camunda/form-playground/tree/106-custom-form-components/custom-field) can be used as an example (use bundled files in the `dist` folder).
  
![Kapture 2023-09-18 at 14 04 18](https://github.com/camunda/form-playground/assets/9433996/5606767d-fd61-4d8e-8f75-4703e4dce139)

This includes some "hacks" to make it work for demo purposes, as of
* The demo pipes some reusable components and utilizes via `window` (similar as we do in the Camunda Modeler)
  * [Set components in `window` inside the app](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/src/app.js#L209)
  * [Use components from `window` in the extensions](https://github.com/camunda/form-playground/blob/106-custom-form-components/custom-field/src/render.js#L6)
* [Extensions need to load themselves into `window`](https://github.com/camunda/form-playground/blob/106-custom-form-components/custom-field/src/render.js#L126) so the app can later [load them easily](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/src/app.js#L196)
* [Preact needs to be deduplicated](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/webpack.config.js#L35)
* Extensions [should be bundled](https://github.com/camunda/form-playground/blob/106-custom-form-components/custom-field/webpack.render.js), e.g. to properly load svg icons, ...

**Comment by nikku** [comment]
Related to (and supporting) the de-duplication effort we plan to work on https://github.com/bpmn-io/internal-docs/issues/819 at the core.

**Comment by pinussilvestrus** [comment]
> This is interesting! To better understand the integration
> 
> * Core: Provides ability to customize (renderer, properties panel)
> * Playground (or "modeler"): Provides the ability to site-load extensions
> 
> Am I correct with this assumption?

This is exactly how it works 👍 Note that I (mis)used the playground here to demo something fast (point 2); this is not necessarily what we are going to build.

@christian-konrad wants to create an epic about further integrating custom form elements in Modelers + Tasklist. This demo is more to showcase the upcoming core features (point 1).

**Comment by pinussilvestrus** [comment]
Some examples what one can build with the demo (sneak peeks from @christian-konrad)

![image](https://github.com/camunda/form-playground/assets/9433996/07c017d2-ea21-4270-ae7e-395bec822740)

![image](https://github.com/camunda/form-playground/assets/9433996/8480010a-070c-4b14-b7a8-f993b661ac6a)

**Comment by pinussilvestrus** [comment]
Demo was built, this issue was achieved.

**Comment by jenishPaladiya-TGS** [comment]
> A basic demo is available via https://106-custom-form-components--camunda-form-playground.netlify.app/
> 
> * Upload extension into the environment, consists of
>   
>   * Rendering extension
>   * Properties Panel extension
>   * Custom styles
> 
> This [example extension](https://github.com/camunda/form-playground/tree/106-custom-form-components/custom-field) can be used as a reference (use bundled files in the `dist` folder).
> 
> ![Kapture 2023-09-18 at 14 04 18](https://private-user-images.githubusercontent.com/9433996/268638995-5606767d-fd61-4d8e-8f75-4703e4dce139.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTA4NDUsIm5iZiI6MTcwMTE1MDU0NSwicGF0aCI6Ii85NDMzOTk2LzI2ODYzODk5NS01NjA2NzY3ZC1mZDYxLTRkOGUtOGY3NS00NzAzZTRkY2UxMzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDU0OTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I1YjJjYzU2MWM3MTNlZDA4ZWI1M2NiNjlkYTA1ZmY2ZGM0MmIyYThjNDQ4NzA2OTBlOTE5NDZmNTYxMjA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZQTV_XY7CuxXk9AklNyd31ozWUv6xeNxSm1m1xvn_wc) [ ![Kapture 2023-09-18 at 14 04 18](https://private-user-images.githubusercontent.com/9433996/268638995-5606767d-fd61-4d8e-8f75-4703e4dce139.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTA4NDUsIm5iZiI6MTcwMTE1MDU0NSwicGF0aCI6Ii85NDMzOTk2LzI2ODYzODk5NS01NjA2NzY3ZC1mZDYxLTRkOGUtOGY3NS00NzAzZTRkY2UxMzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDU0OTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I1YjJjYzU2MWM3MTNlZDA4ZWI1M2NiNjlkYTA1ZmY2ZGM0MmIyYThjNDQ4NzA2OTBlOTE5NDZmNTYxMjA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZQTV_XY7CuxXk9AklNyd31ozWUv6xeNxSm1m1xvn_wc) ](https://private-user-images.githubusercontent.com/9433996/268638995-5606767d-fd61-4d8e-8f75-4703e4dce139.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTA4NDUsIm5iZiI6MTcwMTE1MDU0NSwicGF0aCI6Ii85NDMzOTk2LzI2ODYzODk5NS01NjA2NzY3ZC1mZDYxLTRkOGUtOGY3NS00NzAzZTRkY2UxMzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDU0OTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I1YjJjYzU2MWM3MTNlZDA4ZWI1M2NiNjlkYTA1ZmY2ZGM0MmIyYThjNDQ4NzA2OTBlOTE5NDZmNTYxMjA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZQTV_XY7CuxXk9AklNyd31ozWUv6xeNxSm1m1xvn_wc) [ ](https://private-user-images.githubusercontent.com/9433996/268638995-5606767d-fd61-4d8e-8f75-4703e4dce139.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTA4NDUsIm5iZiI6MTcwMTE1MDU0NSwicGF0aCI6Ii85NDMzOTk2LzI2ODYzODk5NS01NjA2NzY3ZC1mZDYxLTRkOGUtOGY3NS00NzAzZTRkY2UxMzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDU0OTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I1YjJjYzU2MWM3MTNlZDA4ZWI1M2NiNjlkYTA1ZmY2ZGM0MmIyYThjNDQ4NzA2OTBlOTE5NDZmNTYxMjA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZQTV_XY7CuxXk9AklNyd31ozWUv6xeNxSm1m1xvn_wc)
> 
> This includes some "hacks" to make it work for demo purposes, as of
> 
> * The demo pipes some reusable components and utilizes via `window` (similar as we do in the Camunda Modeler)
>   
>   * [Set components in `window` inside the app](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/src/app.js#L209)
>   * [Use components from `window` in the extensions](https://github.com/camunda/form-playground/blob/106-custom-form-components/custom-field/src/render.js#L6)
> * [Extensions need to load themselves into `window`](https://github.com/camunda/form-playground/blob/106-custom-form-components/custom-field/src/render.js#L126) so the app can later [load them easily](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/src/app.js#L196)
> * [Preact needed to be deduplicated in the app](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/webpack.config.js#L35)
> * Extensions [should be bundled](https://github.com/camunda/form-playground/blob/106-custom-form-components/custom-field/webpack.render.js), e.g. to properly load svg icons, ...
> * [The extensions are saved in the local storage](https://github.com/camunda/form-playground/blob/106-custom-form-components/example/src/app.js#L143), as there is no database layer in the playground environment as of now.

is the functionality to add custom form elements via upload js file is now available for use in **1.5.0-alpha.0** version?
because i implemented form js playground in my custom react application and there i cant found option for upload custom form elementes.

**Comment by pinussilvestrus** [comment]
@jenishPaladiya-TGS Unfortunately, the upload function was only for demo purposes and won't be included in form-js or form-playground - also due to security reasons as you can basically inject anything via this upload.

@christian-konrad cc

**Comment by jenishPaladiya-TGS** [comment]
> @jenishPaladiya-TGS Unfortunately, the upload function was only for demo purposes and won't be included in form-js or form-playground - also due to security reasons as you can basically inject anything via this upload.
> 
> @christian-konrad cc

For this **1.5.0-alpha.0** version can i able to create custom elements like (Upload files , ratings , Third party grid , signature pad).
as i'm guessing that the support for custom element is not fully completed.

**Comment by pinussilvestrus** [comment]
> For this **1.5.0-alpha.0** version can i able to create custom elements like (Upload files , ratings , Third party grid , signature pad).

Depending on how your custom components should work, it should be completely possible to build them with the latest version.

For more questions please head over [to our forum](https://forum.bpmn.io/) where you will find people to assist you 👍

**Comment by pinussilvestrus** [comment]
In case you have any feedback / feature request, feel free to [create an issue](https://github.com/bpmn-io/form-js/issues/new/choose).

**Comment by jenishPaladiya-TGS** [comment]
> > For this **1.5.0-alpha.0** version can i able to create custom elements like (Upload files , ratings , Third party grid , signature pad).
> 
> Depending on how your custom components should work, it should be completely possible to build them with the latest version.
> 
> For more questions please head over [to our forum](https://forum.bpmn.io/) where you will find people to assist you 👍

**okay thanks for confirmation**

I have React component (e.g. AGGrid) , can we add react component with all hooks support (e.g. useState, useEffect etc) as a custom element?

I had tried to implement but getting below exception

This is a code of my component
```
const [rowData] = useState([
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxter", price: 72000 }
  ]);

  const [columnDefs] = useState([
    { field: "make" },
    { field: "model" },
    { field: "price" }
  ]);

  return (
    <div className="ag-theme-alpine" style={{ height: 400, width: 600 }}>
      <AgGridReact rowData={rowData} columnDefs={columnDefs}></AgGridReact>
    </div>
  );
```
by this im rendering that component as a custom element

```
return html`
    <div
      class=${formFieldClasses(gridType, {
        errors,
        disabled,
        readonly,
      })}
    >
      <${Label}
        id=${prefixId(id, formId)}
        label=${label}
        required=${required}
      />
      <${GridComp} />
    </div>
  `;
```

and getting below exception

> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.


if i revert the component code to this (Like simply remove UseState hook from component)

```
function GridComp() {
  const [rowData] = [
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxter", price: 72000 },
  ];

  const [columnDefs] = [
    { field: "make" },
    { field: "model" },
    { field: "price" },
  ];

  return (
    <div className="ag-theme-alpine" style={{ height: 500, width: 600 }}>
      <AgGridReact rowData={rowData} columnDefs={columnDefs}></AgGridReact>
    </div>
  );
}
```

Then also giving exception.

> Cannot add property __, object is not extensible
> TypeError: Cannot add property __, object is not extensible

**Comment by pinussilvestrus** [comment]
This looks like a preact duplication error to me, preact has to be included only once. Cf. to our example on how to properly deduplicate preact: https://github.com/bpmn-io/form-js-examples/blob/master/custom-components/webpack.config.js

Requoting to what I mention above

> For more questions please head over [to our forum](https://forum.bpmn.io/) where you will find people to assist you 👍

We want to keep our issues clean. Thanks for your understanding!
